sudo: false
os: linux
language: node_js
node_js: '8.9.2'

services:
  - xvfb

before_install:
- export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;

install:
- npm install
- npm run vscode:prepublish

script:
  - npm test --silent

after_failure:
- "cat /home/travis/build/aaron-bond/better-comments/npm-debug.log"
